### ISSUE TITLE
css navbar z-idex bug

### ISSUE THREAD

**Issue by victorDigital** [victorDigital/betterLectio#4]
A CSS bug that renders navbar elements below content  
the site uses tailwind CSS and daisy UI

A good place to start would be the ```+layout.svelte``` file as it contains the nav element 

<img width="366" alt="image" src="https://user-images.githubusercontent.com/99267380/201480957-9cbd9497-d27d-41cb-9b68-bd29ae2175aa.png">
<img width="234" alt="image" src="https://user-images.githubusercontent.com/99267380/201480989-5270f259-d57b-40eb-b4b7-e5559d9ed04e.png">

**Comment by Asguho** [comment]
Fixed in https://github.com/victorDigital/betterLectio/commit/5d1d69693ab33a92c4bb336eaa0e2e21da732b40!!
